// import dayjs from 'dayjs';

// import {
//   TReservationObject,
//   ReservationActivityStatusEnum,
//   ReservationStatusEnum,
// } from '@/types/api/reservation/index';

// import licensePlateOptionsDummy from '@/utils/dummies/reservation/licensePlateOptionsDummy';
// import driveNameOptionsDummy from '@/utils/dummies/reservation/driverNameOptionsDummy';

// const todayDate = dayjs(new Date());

// export const initialReservations: TReservationObject[] = [
//   {
//     status: ReservationStatusEnum.ACTIVE,
//     activity: ReservationActivityStatusEnum.DOCKING,
//     id: 1,
//     licensePlate: 'AD-345523-WI',
//     vendor: 'PT. Maju Makmur',
//     driver: driveNameOptionsDummy[5].value,
//     dockNo: 'A 01',
//     duration: 4,
//     workId: 'WO245455RE',
//     expectedCheckInTime: todayDate
//       .subtract(30, 'minute')
//       .subtract(30, 'second'),
//     actualCheckInTime: todayDate.subtract(25, 'minute'),
//     waitingTime: todayDate.subtract(10, 'minute').subtract(10, 'second'),
//     dockingTime: todayDate.subtract(5, 'minute').subtract(40, 'second'),
//     checkOutTime: null,
//     rfid: 'RF-234324532',
//     isPriority: false,
//     warehouse: 'Pabrik A',
//     workOrderName: 'Work Order name',
//     workOrders: [
//       {
//         id: 'PC-2227346',
//         amount: 25000,
//         unit: 'kg',
//         item: 'NPK (Nitrogen, Fosfor, Kalium) campuran',
//       },
//       {
//         id: 'PC-2326746',
//         amount: 10000,
//         unit: 'kg',
//         item: 'SP-36 (Super Phosphate)',
//       },
//     ],
//   },
//   {
//     id: 2,
//     status: ReservationStatusEnum.ACTIVE,
//     activity: ReservationActivityStatusEnum.WAITING,
//     licensePlate: licensePlateOptionsDummy[7].value,
//     vendor: 'PT XYZ Sejahtera',
//     driver: driveNameOptionsDummy[6].value,
//     dockNo: 'A 05',
//     duration: 2,
//     workId: 'WO15646',
//     expectedCheckInTime: todayDate.subtract(25, 'minute'),
//     actualCheckInTime: todayDate.subtract(10, 'minute'),
//     waitingTime: todayDate.subtract(2, 'minute').subtract(30, 'second'),
//     dockingTime: null,
//     checkOutTime: null,
//     rfid: 'RF-234324532',
//     isPriority: false,
//     warehouse: 'Pabrik A',
//     workOrderName: 'Work Order name',
//     workOrders: [
//       {
//         id: 'PC-2227346',
//         amount: 25000,
//         unit: 'kg',
//         item: 'NPK (Nitrogen, Fosfor, Kalium) campuran',
//       },
//     ],
//   },
//   {
//     id: 3,
//     status: ReservationStatusEnum.ACTIVE,
//     activity: ReservationActivityStatusEnum.CHECKEDIN,
//     licensePlate: licensePlateOptionsDummy[1].value,
//     vendor: 'PT Membangun ID',
//     driver: driveNameOptionsDummy[0].value,
//     dockNo: '',
//     workId: 'WO25847',
//     duration: 2,
//     isPriority: false,
//     expectedCheckInTime: todayDate.subtract(20, 'minute'),
//     actualCheckInTime: todayDate.subtract(10, 'minute'),
//     waitingTime: null,
//     dockingTime: null,
//     checkOutTime: null,
//     rfid: 'RF-234324532',
//     warehouse: 'Pabrik A',
//     workOrderName: 'Work Order name',
//     workOrders: [
//       {
//         id: 'PC-2227346',
//         amount: 25000,
//         unit: 'kg',
//         item: 'NPK (Nitrogen, Fosfor, Kalium) campuran',
//       },
//     ],
//   },
//   {
//     id: 4,
//     status: ReservationStatusEnum.ACTIVE,
//     activity: ReservationActivityStatusEnum.SCHEDULED,
//     licensePlate: licensePlateOptionsDummy[1].value,
//     vendor: 'PT Membangun ID',
//     driver: driveNameOptionsDummy[0].value,
//     dockNo: '',
//     workId: 'WO96421',
//     isPriority: false,
//     duration: 3,
//     expectedCheckInTime: todayDate.subtract(1, 'hour'),
//     actualCheckInTime: null,
//     waitingTime: null,
//     dockingTime: null,
//     checkOutTime: null,
//     rfid: 'RF-234324532',
//     warehouse: 'Pabrik A',
//     workOrderName: 'Work Order name',
//     workOrders: [
//       {
//         id: 'PC-2227346',
//         amount: 25000,
//         unit: 'kg',
//         item: 'NPK (Nitrogen, Fosfor, Kalium) campuran',
//       },
//       {
//         id: 'PC-2326746',
//         amount: 10000,
//         unit: 'kg',
//         item: 'SP-36 (Super Phosphate)',
//       },
//     ],
//   },
//   {
//     id: 5,
//     status: ReservationStatusEnum.ACTIVE,
//     activity: ReservationActivityStatusEnum.CHECKEDOUT,
//     licensePlate: licensePlateOptionsDummy[2].value,
//     vendor: 'PT. Jaya Sakti',
//     duration: 5,
//     isPriority: false,
//     driver: driveNameOptionsDummy[2].value,
//     dockNo: '',
//     workId: 'WO78215',
//     expectedCheckInTime: todayDate.subtract(1, 'hour'),
//     actualCheckInTime: todayDate.subtract(45, 'minute'),
//     waitingTime: todayDate.subtract(15, 'minute').subtract(15, 'second'),
//     dockingTime: todayDate.subtract(10, 'minute').subtract(10, 'second'),
//     checkOutTime: todayDate.subtract(5, 'minute'),
//     rfid: 'RF-234324532',
//     warehouse: 'Pabrik A',
//     workOrderName: 'Work Order name',
//     workOrders: [
//       {
//         id: 'PC-2227346',
//         amount: 25000,
//         unit: 'kg',
//         item: 'NPK (Nitrogen, Fosfor, Kalium) campuran',
//       },
//       {
//         id: 'PC-2326746',
//         amount: 10000,
//         unit: 'kg',
//         item: 'SP-36 (Super Phosphate)',
//       },
//     ],
//   },
//   {
//     id: 6,
//     duration: 1,
//     status: ReservationStatusEnum.ACTIVE,
//     activity: ReservationActivityStatusEnum.CHECKEDOUT,
//     licensePlate: licensePlateOptionsDummy[2].value,
//     vendor: 'PT Nusantara',
//     driver: driveNameOptionsDummy[2].value,
//     dockNo: '',
//     isPriority: false,
//     workId: 'WO419832',
//     expectedCheckInTime: todayDate.subtract(1, 'hour'),
//     actualCheckInTime: todayDate.subtract(20, 'minute'),
//     waitingTime: todayDate.subtract(14, 'minute').subtract(15, 'second'),
//     dockingTime: todayDate.subtract(10, 'minute').subtract(20, 'second'),
//     checkOutTime: todayDate.subtract(6, 'minute'),
//     rfid: 'RF-234324532',
//     warehouse: 'Pabrik A',
//     workOrderName: 'Work Order name',
//     workOrders: [
//       {
//         id: 'PC-2227346',
//         amount: 25000,
//         unit: 'kg',
//         item: 'NPK (Nitrogen, Fosfor, Kalium) campuran',
//       },
//       {
//         id: 'PC-2326746',
//         amount: 10000,
//         unit: 'kg',
//         item: 'SP-36 (Super Phosphate)',
//       },
//     ],
//   },
//   {
//     id: 7,
//     status: ReservationStatusEnum.ACTIVE,
//     activity: ReservationActivityStatusEnum.WAITING,
//     isPriority: false,
//     licensePlate: licensePlateOptionsDummy[6].value,
//     vendor: 'PT Jaya Sakti',
//     driver: driveNameOptionsDummy[3].value,
//     dockNo: 'B 04',
//     duration: 2,
//     workId: 'WO732485',
//     expectedCheckInTime: todayDate.subtract(30, 'minute').subtract(5, 'second'),
//     actualCheckInTime: todayDate.subtract(15, 'minute').subtract(15, 'second'),
//     waitingTime: todayDate.subtract(10, 'minute').subtract(5, 'second'),
//     dockingTime: null,
//     checkOutTime: null,
//     rfid: 'RF-234324532',
//     warehouse: 'Pabrik A',
//     workOrderName: 'Work Order name',
//     workOrders: [
//       {
//         id: 'PC-2227346',
//         amount: 25000,
//         unit: 'kg',
//         item: 'NPK (Nitrogen, Fosfor, Kalium) campuran',
//       },
//       {
//         id: 'PC-2326746',
//         amount: 10000,
//         unit: 'kg',
//         item: 'SP-36 (Super Phosphate)',
//       },
//     ],
//   },
//   {
//     id: 8,
//     status: ReservationStatusEnum.ACTIVE,
//     activity: ReservationActivityStatusEnum.WAITING,
//     licensePlate: licensePlateOptionsDummy[0].value,
//     vendor: 'PT Nusantara',
//     driver: driveNameOptionsDummy[1].value,
//     dockNo: 'C 06',
//     isPriority: false,
//     duration: 2,
//     workId: 'WO889976',
//     expectedCheckInTime: todayDate
//       .subtract(22, 'minute')
//       .subtract(25, 'second'),
//     actualCheckInTime: todayDate.subtract(18, 'minute'),
//     waitingTime: todayDate.subtract(11, 'minute').subtract(25, 'second'),
//     dockingTime: null,
//     checkOutTime: null,
//     rfid: 'RF-234324532',
//     warehouse: 'Pabrik A',
//     workOrderName: 'Work Order name',
//     workOrders: [
//       {
//         id: 'PC-2227346',
//         amount: 25000,
//         unit: 'kg',
//         item: 'NPK (Nitrogen, Fosfor, Kalium) campuran',
//       },
//     ],
//   },
//   {
//     id: 9,
//     status: ReservationStatusEnum.ACTIVE,
//     activity: ReservationActivityStatusEnum.DOCKING,
//     isPriority: false,
//     licensePlate: licensePlateOptionsDummy[6].value,
//     vendor: 'PT Jaya Sakti',
//     driver: driveNameOptionsDummy[3].value,
//     dockNo: 'B 10',
//     duration: 2,
//     workId: 'WO097645',
//     expectedCheckInTime: todayDate.subtract(18, 'minute'),
//     actualCheckInTime: todayDate.subtract(11, 'minute'),
//     waitingTime: todayDate.subtract(10, 'minute').subtract(34, 'second'),
//     dockingTime: todayDate.subtract(5, 'minute'),
//     checkOutTime: null,
//     rfid: 'RF-234324532',
//     warehouse: 'Pabrik A',
//     workOrderName: 'Work Order name',
//     workOrders: [
//       {
//         id: 'PC-2227346',
//         amount: 10000,
//         unit: 'kg',
//         item: 'SP-36 (Super Phosphate)',
//       },
//       {
//         id: 'PC-33327346',
//         amount: 5000,
//         unit: 'kg',
//         item: 'KCl (Kalium Klorida)',
//       },
//     ],
//   },
//   {
//     id: 10,
//     status: ReservationStatusEnum.ACTIVE,
//     activity: ReservationActivityStatusEnum.DOCKING,
//     licensePlate: licensePlateOptionsDummy[5].value,
//     vendor: 'CV Delta Bersama',
//     isPriority: false,
//     driver: driveNameOptionsDummy[4].value,
//     dockNo: 'B 05',
//     duration: 2,
//     workId: 'WO872134',
//     expectedCheckInTime: todayDate.subtract(10, 'minute'),
//     actualCheckInTime: todayDate.subtract(9, 'minute').subtract(27, 'second'),
//     waitingTime: todayDate.subtract(8, 'minute').subtract(13, 'second'),
//     dockingTime: todayDate.subtract(2, 'minute'),
//     checkOutTime: null,
//     rfid: 'RF-234324532',
//     warehouse: 'Pabrik A',
//     workOrderName: 'Work Order name',
//     workOrders: [
//       {
//         id: 'PC-33327346',
//         amount: 5000,
//         unit: 'kg',
//         item: 'KCl (Kalium Klorida)',
//       },
//     ],
//   },
//   {
//     id: 11,
//     status: ReservationStatusEnum.ACTIVE,
//     activity: ReservationActivityStatusEnum.DOCKING,
//     isPriority: false,
//     licensePlate: licensePlateOptionsDummy[7].value,
//     vendor: 'PT XYZ Sejahtera',
//     driver: driveNameOptionsDummy[6].value,
//     dockNo: 'C 05',
//     duration: 2,
//     workId: 'WO876543',
//     expectedCheckInTime: todayDate.subtract(25, 'minute'),
//     actualCheckInTime: todayDate.subtract(15, 'minute').subtract(15, 'second'),
//     waitingTime: todayDate.subtract(14, 'minute').subtract(45, 'second'),
//     dockingTime: todayDate.subtract(10, 'minute'),
//     checkOutTime: null,
//     rfid: 'RF-234324532',
//     warehouse: 'Pabrik A',
//     workOrderName: 'Work Order name',
//     workOrders: [
//       {
//         id: 'PC-11127346',
//         amount: 15000,
//         unit: 'kg',
//         item: 'Urea',
//       },
//     ],
//   },
//   {
//     id: 12,
//     status: ReservationStatusEnum.ACTIVE,
//     activity: ReservationActivityStatusEnum.DOCKING,
//     licensePlate: licensePlateOptionsDummy[4].value,
//     vendor: 'UD Sinar Jaya',
//     driver: driveNameOptionsDummy[7].value,
//     isPriority: false,
//     dockNo: 'B 07',
//     duration: 2,
//     workId: 'WO98646',
//     expectedCheckInTime: todayDate.subtract(15, 'minute'),
//     actualCheckInTime: todayDate.subtract(10, 'minute').subtract(15, 'second'),
//     waitingTime: todayDate.subtract(9, 'minute').subtract(45, 'second'),
//     dockingTime: todayDate.subtract(5, 'minute'),
//     checkOutTime: null,
//     rfid: 'RF-234324532',
//     warehouse: 'Pabrik A',
//     workOrderName: 'Work Order name',
//     workOrders: [
//       {
//         id: 'PC-33327346',
//         amount: 5000,
//         unit: 'kg',
//         item: 'KCl (Kalium Klorida)',
//       },
//       {
//         id: 'PC-11127346',
//         amount: 15000,
//         unit: 'kg',
//         item: 'Urea',
//       },
//     ],
//   },
//   {
//     id: 13,
//     status: ReservationStatusEnum.ACTIVE,
//     activity: ReservationActivityStatusEnum.DOCKING,
//     licensePlate: licensePlateOptionsDummy[6].value,
//     vendor: 'PT Jaya Sakti',
//     driver: driveNameOptionsDummy[3].value,
//     isPriority: false,
//     dockNo: 'B 01',
//     duration: 2,
//     workId: 'WO097632',
//     expectedCheckInTime: todayDate.subtract(15, 'minute'),
//     actualCheckInTime: todayDate.subtract(12, 'minute').subtract(15, 'second'),
//     waitingTime: todayDate.subtract(10, 'minute').subtract(45, 'second'),
//     dockingTime: todayDate.subtract(7, 'minute'),
//     checkOutTime: null,
//     rfid: 'RF-234324532',
//     warehouse: 'Pabrik A',
//     workOrderName: 'Work Order name',
//     workOrders: [
//       {
//         id: 'PC-33327346',
//         amount: 5000,
//         unit: 'kg',
//         item: 'KCl (Kalium Klorida)',
//       },
//     ],
//   },
//   {
//     id: 14,
//     status: ReservationStatusEnum.ACTIVE,
//     activity: ReservationActivityStatusEnum.WAITING,
//     licensePlate: licensePlateOptionsDummy[2].value,
//     vendor: 'PT LuasTani',
//     driver: driveNameOptionsDummy[8].value,
//     isPriority: true,
//     dockNo: 'A 10',
//     duration: 2,
//     workId: 'WO907643',
//     expectedCheckInTime: todayDate.subtract(15, 'minute'),
//     actualCheckInTime: todayDate.subtract(10, 'minute').subtract(15, 'second'),
//     waitingTime: todayDate.subtract(9, 'minute').subtract(45, 'second'),
//     dockingTime: null,
//     checkOutTime: null,
//     rfid: 'RF-234324532',
//     warehouse: 'Pabrik A',
//     workOrderName: 'Work Order name',
//     workOrders: [
//       {
//         id: 'PC-11127346',
//         amount: 15000,
//         unit: 'kg',
//         item: 'Urea',
//       },
//     ],
//   },
// ];
